### ISSUE TITLE
The map view displays the image without any overlay (two points, user localization marker) visible (Android 10)

### ISSUE THREAD

**Issue by jnareb** [WojciechKuz/Mappic#5]
When going from list of maps to an individual map, for me the map view displays only the photo of the map or plan; no markers are visible.

I expect to see at least 2 markers for 2 points used to find localization of the map, its scale and orientation, added in 2nd and 3rd step of adding a map. I would also expect to either see the marker denoting the position and orientation of the user (denoting current localization), or information that the user is outside the bounds of the map.

Examining the logcat, everything looks all right (with the exception of not being able to extract rotation information from EXIF data for some strange reason).
```
D>>> Renderer is set.
W>>> Can't get Permission manager. Activity not created yet !!!
D>>> Got mapImg Uri
D>>> Got points
D>>> onStart, initializing imageSizeCalc()
E>>> Rotation tag in image exif data not found. cannot display it correctly.
D>>> SURFACE CHANGE Surface change - w: 1080, h: 1731.
[...]
D>>> Original size: 3456x4608, View size: 1080x1731, Scaled image size: 1080x1440.
D>>> User is in 53.011684 N, 18.585445 E
D>>> Original point: Point(3918, 961)
D>>> In View point: Point(3918, 961)
D>>> OpenGL user point: 0.7907279, 0.48548526, 0.0
D>>> userMarker [0.7907279, 0.48548526]
D>>> CLEAR
```
But then, the following error happens:
```
E>>> call to OpenGL ES API with no current context (logged once per thread)
```

**Note:** my smartphone is Nokia 6.1, with Android 10 (API Level 29),

**Comment by WojciechKuz** [comment]
- In viewMap mode only user Marker should be visible. Make sure location setting is enabled and app permissions are set.
- User marker should show up in viewMap with slight delay of 1-2 seconds.
- Error about rotation tag is not important. It's due to images not having information about it's orientation. Despite this error images usually are displayed in correct orientation. This error will be degraded to warning.
- Position of userMarker [0.7907279, 0.48548526] is in screen bounds and should be displayed. This issue will be investigated.
- "call to OpenGL ES API with no current context (logged once per thread)" shows up for me as well, but has no impact on app's behaviour. This will be investigated as well.

**Comment by WojciechKuz** [comment]
- In viewMap mode only user Marker should be visible. Make sure location setting is enabled and app permissions are set.
- User marker should show up in viewMap with slight delay of 1-2 seconds.
- Error about rotation tag is not important. It's due to images not having information about it's orientation. Despite this error images usually are displayed in correct orientation. This error is now degraded to warning.
- **Issue with not displaying user marker should be fixed now.** Fix tested on 2 Android 10 devices - emulated pixel 3 and physical Xiaomi Mi A2 Lite. Please check if it works on your device.
- "call to OpenGL ES API with no current context (logged once per thread)" shows up for me as well, but has no impact on app's behaviour. I have searched for similar issues, my code already contains proposed solutions, but error still appears. Since it has no impact on app, it won't be fixed.
